# Generated by Django 5.2.13 on 2026-05-05 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('price', models.PositiveIntegerField(help_text='In ₹ per unit.')),
                ('unit', models.CharField(blank=True, default='each', help_text="e.g. 'each', 'per piece', '200 ml'", max_length=30)),
                ('icon', models.CharField(blank=True, default='🥘', help_text='Optional emoji shown next to the add-on (e.g. 🥣, 🫓, 🍮).', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=80)),
                ('plan_slug', models.CharField(max_length=60)),
                ('plan_name', models.CharField(max_length=80)),
                ('plan_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('meal_time', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner'), ('both', 'Lunch + Dinner')], default='lunch', max_length=10)),
                ('delivery_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('addons', models.JSONField(blank=True, default=list)),
                ('addons_total', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=12)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('price', models.PositiveIntegerField(help_text='In ₹.')),
                ('unit', models.CharField(choices=[('per meal', 'per meal'), ('per month', 'per month'), ('per week', 'per week'), ('per meal (10+ qty)', 'per meal (10+ qty)')], default='per meal', max_length=40)),
                ('items', models.TextField(help_text='One line per item. e.g.\n4 Roti\nSabzi\nDal\nRice\nSalad')),
                ('badge', models.CharField(blank=True, help_text="Optional. e.g. 'Most Popular', 'Best Value'.", max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Ravinarayan PG & Tiffin Service', max_length=120)),
                ('short_name', models.CharField(default='Ravinarayan Tiffin', help_text='Used in compact spots like the nav.', max_length=60)),
                ('tagline', models.CharField(blank=True, default='Fresh homemade tiffin, delivered daily.', max_length=200)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=30)),
                ('whatsapp_number', models.CharField(default='919876543210', help_text="International format, digits only — no '+' or spaces. e.g. 919876543210", max_length=20)),
                ('email', models.EmailField(default='orders@ravinarayan.example', max_length=254)),
                ('address', models.CharField(default='Shop 12, Market Road, Pune 411001', max_length=300)),
                ('hours', models.CharField(default='Mon – Sat, 10:00 AM – 9:00 PM', max_length=120)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('meal_time', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('items', models.TextField(help_text='One item per line.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('day_of_week', 'meal_time'),
                'unique_together': {('day_of_week', 'meal_time')},
            },
        ),
    ]
