# Generated by Django 5.2.13 on 2026-05-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0002_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='image_filename',
            field=models.CharField(blank=True, help_text="Filename inside static/img/ — e.g. 'plan-daily.jpg'. Leave blank to use plan-<slug>.jpg.", max_length=80),
        ),
    ]
