# Generated by Django 5.2.13 on 2026-05-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0004_two_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
