# Generated by Django 5.2.13 on 2026-05-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0005_order_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Home delivery'), ('pickup', 'Pick up from counter')], db_index=True, default='delivery', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='plan_unit',
            field=models.CharField(blank=True, help_text="Snapshot of plan unit at order time (e.g. 'per meal').", max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_center_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of your kitchen / business hub. Leave blank to disable geofencing.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_center_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of your kitchen / business hub.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum delivery distance in km. 0 = no geofence (only the area dropdown is enforced).', max_digits=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_enabled',
            field=models.BooleanField(default=True, help_text='When on, customers can choose to pick up from the counter instead of delivery.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
