# Generated by Django 5.2.13 on 2026-05-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0006_geofence_pickup_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(default='Pune', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='country',
            field=models.CharField(default='India', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='country_code',
            field=models.CharField(default='IN', help_text='ISO 2-letter — e.g. IN, US.', max_length=2),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ga_measurement_id',
            field=models.CharField(blank=True, help_text='Google Analytics 4 Measurement ID (e.g. G-XXXXXXXXXX). Leave blank to disable.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_business_url',
            field=models.URLField(blank=True, help_text='Your Google Business Profile sharable link.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postal_code',
            field=models.CharField(default='411001', max_length=12),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_keywords',
            field=models.CharField(blank=True, default='tiffin service, tiffin near me, homemade tiffin, lunch tiffin, monthly tiffin, PG tiffin, office lunch, ghar ka khana, veg tiffin, dabba service', help_text='Comma-separated keywords. Used in meta keywords + helps drive copy.', max_length=400),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_description',
            field=models.CharField(blank=True, default='Fresh, homemade veg tiffin service. Daily lunch & dinner at ₹70 per meal or ₹3200 per month. Lunch by 1 PM, dinner by 8:30 PM. FSSAI compliant kitchen. Order on WhatsApp or our website.', help_text='160-300 chars. Used as the site-wide default meta description.', max_length=320),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Your Google Business Profile / maps listing URL.'),
        ),
    ]
