# Generated by Django 5.2.13 on 2026-05-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0007_seo_local_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='Metcity, Bahadurgarh, Jhajjar district, Haryana 124507', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(default='Jhajjar', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='postal_code',
            field=models.CharField(default='124507', max_length=12),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_keywords',
            field=models.CharField(blank=True, default='tiffin service Jhajjar, tiffin in Metcity, tiffin in Yakubpur, tiffin Bahadurgarh, tiffin Farrukhnagar, homemade tiffin Haryana, monthly tiffin PG, lunch tiffin office, veg tiffin near me, dabba service Jhajjar, tiffin near me, ghar ka khana', help_text='Comma-separated keywords. Used in meta keywords + helps drive copy.', max_length=400),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.CharField(blank=True, default='Fresh homemade veg tiffin service in Jhajjar — Metcity, Yakubpur, Bahadurgarh & Farrukhnagar. Daily lunch & dinner at ₹70 per meal or ₹3200 per month. Lunch by 1 PM, dinner by 8:30 PM. FSSAI compliant. Order on WhatsApp.', help_text='160-300 chars. Used as the site-wide default meta description.', max_length=320),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='state',
            field=models.CharField(default='Haryana', max_length=80),
        ),
    ]
