# Generated by Django 5.2.13 on 2026-05-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0012_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum delivery distance in km. 0 or 2 = no hard cap; delivery is free up to 2 km, then ₹10 per started 2 km slab.', max_digits=5),
        ),
    ]
