# Generated by Django 5.2.13 on 2026-05-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0013_alter_sitesettings_delivery_radius_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plan_price_on_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='available_day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='For day-specific plans such as rice bowls.', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.CharField(choices=[('tiffin', 'Tiffin'), ('rice_bowl', 'Rice bowl'), ('snack', 'Snack')], db_index=True, default='tiffin', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_single_meal_price',
            field=models.PositiveIntegerField(blank=True, help_text='Optional monthly price when customer chooses only lunch or only dinner.', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='order_cutoff_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='order_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_on_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='unit',
            field=models.CharField(choices=[('per meal', 'per meal'), ('per month', 'per month'), ('per week', 'per week'), ('per meal (10+ qty)', 'per meal (10+ qty)'), ('per bowl', 'per bowl'), ('per piece', 'per piece'), ('price on request', 'price on request')], default='per meal', max_length=40),
        ),
    ]
