# Generated by Django 5.2.13 on 2026-05-14 10:57

from django.db import migrations, models


NEW_DESCRIPTION = (
    "Fresh homemade veg tiffin service in Jhajjar — Metcity, Yakubpur, Bahadurgarh & Farrukhnagar. "
    "Daily tiffin from ₹70, monthly packages from ₹1800, and today's rice bowl at ₹60. "
    "FSSAI compliant. Order on WhatsApp."
)


def forwards(apps, schema_editor):
    SiteSettings = apps.get_model("tiffin", "SiteSettings")
    site = SiteSettings.objects.first()
    if site is not None and (
        "₹3500 per month" in (site.site_description or "")
        or "₹3200 per month" in (site.site_description or "")
    ):
        site.site_description = NEW_DESCRIPTION
        site.save(update_fields=["site_description"])


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0015_menu_expansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.CharField(blank=True, default=NEW_DESCRIPTION, help_text='160-300 chars. Used as the site-wide default meta description.', max_length=320),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
