# Generated by Django 5.2.13 on 2026-06-17 11:08

from django.db import migrations, models


GOOGLE_REVIEW_URL = "https://share.google/kvPQQtTdyJ65cEiqi"


def update_google_review_url(apps, schema_editor):
    SiteSettings = apps.get_model("tiffin", "SiteSettings")
    SiteSettings.objects.update(google_business_url=GOOGLE_REVIEW_URL)


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0019_complete_local_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='google_business_url',
            field=models.URLField(blank=True, default=GOOGLE_REVIEW_URL, help_text='Google Business Profile sharable link used by the /review/ redirect.'),
        ),
        migrations.RunPython(update_google_review_url, migrations.RunPython.noop),
    ]
